CREATE TABLE Student (
  StudentID INT AUTO_INCREMENT KEY,
  Name VARCHAR(100),
  UniName VARCHAR(100) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  UNIQUE(Email)
);

CREATE TABLE Course (
  CourseID INT AUTO_INCREMENT KEY,
  Dept VARCHAR(4) NOT NULL,
  Num INTEGER NOT NULL,  
  CourseName VARCHAR(100), 
  Credits INTEGER NOT NULL
);